### ISSUE TITLE
Can I ask some info?

### ISSUE THREAD

**Issue by lpnam** [hackintosh-efi/ROG-STRIX-B760-I-GAMING-OpenCore#3]
Hi, I'm new with Hackintosh, can i have some info for this
1. Hackintosh will work with any RX6600 card right?
2. This "WiFi Card: BCM94360CS2" is default wifi card of Rog Strix B760i or we need replace with this one?

Thanks!

**Comment by WuLongMiTaoLaiYiDa** [comment]
1.Yes, any RX6600 can be used
2.The default network card is an Intel wireless network card, and you can install 94360cs2 through an adapter board

**Comment by lpnam** [comment]
Thanks you so much!
