### ISSUE TITLE
Is this board CNVI locked?

### ISSUE THREAD

**Issue by ghost** [hackintosh-efi/ROG-STRIX-B760-I-GAMING-OpenCore#4]
I noticed that you've stated that this setup uses BCM94360CS2 as a WiFi card, which is not the default one. Did you just remove the WiFi chip and replaced it? Or are you using a M2 adapter?

**Comment by londbell** [comment]
> I noticed that you've stated that this setup uses BCM94360CS2 as a WiFi card, which is not the default one. Did you just remove the WiFi chip and replaced it? Or are you using a M2 adapter?

no problem,this board can both use cnvi or non-cnvi card;

**Comment by WuLongMiTaoLaiYiDa** [comment]
replaced it with BCM94360CS2 to M.2 Adapter 
![IMG_8910](https://github.com/hackintosh-club/ROG-STRIX-B760-I-GAMING-OpenCore/assets/44227759/f23cfc38-1319-4c46-a71c-18ef16cc897b)
![IMG_8911](https://github.com/hackintosh-club/ROG-STRIX-B760-I-GAMING-OpenCore/assets/44227759/118b7b6d-1602-4dfc-bbbd-7b13daa02b65)

**Comment by londbell** [comment]
> replaced it with BCM94360CS2 to M.2 Adapter ![IMG_8910](https://private-user-images.githubusercontent.com/44227759/292197021-f23cfc38-1319-4c46-a71c-18ef16cc897b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjEwMjUsIm5iZiI6MTcwMzE2MDcyNSwicGF0aCI6Ii80NDIyNzc1OS8yOTIxOTcwMjEtZjIzY2ZjMzgtMTMxOS00YzQ2LWE3MWMtMThlZjE2Y2M4OTdiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOGVmMGMxYWE0YzY0MDVmNzNiN2JjNmRmY2M2ZTZjNzA2YmIyZmNkY2I4Mzc2ZTRlMjczMTdhNzhkMDMyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kc6jyCjJoe99CLd2vTJzsDz2KlOkq8TlHK66Nj9YTV4) ![IMG_8911](https://private-user-images.githubusercontent.com/44227759/292197033-118b7b6d-1602-4dfc-bbbd-7b13daa02b65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjEwMjUsIm5iZiI6MTcwMzE2MDcyNSwicGF0aCI6Ii80NDIyNzc1OS8yOTIxOTcwMzMtMTE4YjdiNmQtMTYwMi00ZGZjLWJiYmQtN2IxM2RhYTAyYjY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzU3MWMyMmMzNjgyY2VjYjcxMDQ5YTc2ODRlNzk4OTQ5OGU3NDkxYzllOWVhNGQ4NjM1MzE3MDQxMTU5NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBVO3lv8LS6Jo-CTFrtbVjiWZIT86m6pxiiLnAQKafw)

直接使用新版Z3/Z4或者fenvi的94352z（也就是海外的94360NG）就可以了，尺寸和正常M2网卡一样，不需要切割VRM装甲或者用软排线转接卡后放平白果卡

**Comment by WuLongMiTaoLaiYiDa** [comment]
> > replaced it with BCM94360CS2 to M.2 Adapter ![IMG_8910](https://private-user-images.githubusercontent.com/44227759/292197021-f23cfc38-1319-4c46-a71c-18ef16cc897b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjEwMjUsIm5iZiI6MTcwMzE2MDcyNSwicGF0aCI6Ii80NDIyNzc1OS8yOTIxOTcwMjEtZjIzY2ZjMzgtMTMxOS00YzQ2LWE3MWMtMThlZjE2Y2M4OTdiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNlOGVmMGMxYWE0YzY0MDVmNzNiN2JjNmRmY2M2ZTZjNzA2YmIyZmNkY2I4Mzc2ZTRlMjczMTdhNzhkMDMyMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kc6jyCjJoe99CLd2vTJzsDz2KlOkq8TlHK66Nj9YTV4) ![IMG_8911](https://private-user-images.githubusercontent.com/44227759/292197033-118b7b6d-1602-4dfc-bbbd-7b13daa02b65.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxNjEwMjUsIm5iZiI6MTcwMzE2MDcyNSwicGF0aCI6Ii80NDIyNzc1OS8yOTIxOTcwMzMtMTE4YjdiNmQtMTYwMi00ZGZjLWJiYmQtN2IxM2RhYTAyYjY1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIxVDEyMTIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3YzU3MWMyMmMzNjgyY2VjYjcxMDQ5YTc2ODRlNzk4OTQ5OGU3NDkxYzllOWVhNGQ4NjM1MzE3MDQxMTU5NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBVO3lv8LS6Jo-CTFrtbVjiWZIT86m6pxiiLnAQKafw)
> 
> 直接使用新版Z3/Z4或者fenvi的94352z（也就是海外的94360NG）就可以了，尺寸和正常M2网卡一样，不需要切割VRM装甲或者用软排线转接卡后放平白果卡

NG对路由器有要求，3*3mimo才支持NSS2，普通路由器只能达成NSS1，俗称“单臂”（单天线），此情况下满速433兆

**Comment by hoangcongtuan** [comment]
> replaced it with BCM94360CS2 to M.2 Adapter ![IMG_8910](https://github.com/hackintosh-club/ROG-STRIX-B760-I-GAMING-OpenCore/assets/44227759/f23cfc38-1319-4c46-a71c-18ef16cc897b) ![IMG_8911](https://github.com/hackintosh-club/ROG-STRIX-B760-I-GAMING-OpenCore/assets/44227759/118b7b6d-1602-4dfc-bbbd-7b13daa02b65)

How you put this to the main board?
