### ISSUE TITLE
Bluetooth kexts

### ISSUE THREAD

**Issue by ciumbuntu** [hackintosh-efi/ROG-STRIX-B760-I-GAMING-OpenCore#5]
Bluetooth working oob:
BlueToolFixup.kext
IntelBluetoothFirmware.kext
IntelBTPatcher.kext

[BTkexts.zip](https://github.com/hackintosh-club/ROG-STRIX-B760-I-GAMING-OpenCore/files/13781509/BTkexts.zip)

**Comment by mrasong** [comment]
What does OOB mean ？

**Comment by ciumbuntu** [comment]
out of the box: did u test the kexts?

**Comment by mrasong** [comment]
NOT tested on this one, but other with Intel WLAN.

**Comment by WuLongMiTaoLaiYiDa** [comment]
Thank you for providing the intel driver
