### ISSUE TITLE
WiFi kext

### ISSUE THREAD

**Issue by ciumbuntu** [hackintosh-efi/ROG-STRIX-B760-I-GAMING-OpenCore#6]
Working oob
[AirportItlwm.kext.zip](https://github.com/hackintosh-club/ROG-STRIX-B760-I-GAMING-OpenCore/files/13781512/AirportItlwm.kext.zip)

**Comment by WuLongMiTaoLaiYiDa** [comment]
Thank you for providing the intel driver
